default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: purrpurr_development

test:
  <<: *default
  database: purrpurr_test

production:
  <<: *default
  database: purrpurr
